In [3]:
import os
import pandas as pd

In [5]:
base_dir = base_dir = os.path.dirname(os.getcwd())
data_dir = os.path.join(base_dir, "data")

 ## 🗂️ **Preparing Data - Combining Dataset & Merging Coordinates Hong Kong**

In [ ]:
hong_kong_data_dir = os.path.join(base_dir, "data", "Hong Kong")

if not os.path.exists(hong_kong_data_dir):
    raise FileNotFoundError("Hong Kong data directory not found.")

In [ ]:
import glob

hong_kong_river_data_files = glob.glob(os.path.join(hong_kong_data_dir, "*river_quality*.csv"))
print(hong_kong_river_data_files)

['/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (6).csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (26).csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (30).csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (10).csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (11).csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (31).csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (27).csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (7).csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (16).csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (20).csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (21).csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (1).csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (17).csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (14).csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (34).csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (22).csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality.csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (2).csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (18).csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (3).csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (19).csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (23).csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (15).csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (32).csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (24).csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (4).csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (28).csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (8).csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (12).csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (9).csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (13).csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (29).csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/hong_kong_river_quality_combined.csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (5).csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (25).csv', '/Users/nqb/Documents/river-water-quality-prediction-contamination-detection/data/Hong Kong/river_quality (33).csv']

In [ ]:
hong_kong_df = [pd.read_csv(file) for file in hong_kong_river_data_files]
Hong_Kong_River_Water_Quality_df = pd.concat(hong_kong_df, ignore_index=True)
Hong_Kong_River_Water_Quality_df.head()

/var/folders/n2/km_1mc9n48g26dqmvhjr0w8m0000gn/T/ipykernel_80632/1450419363.py:1: DtypeWarning: Columns (25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  hong_kong_df = [pd.read_csv(file) for file in hong_kong_river_data_files]

,Water Control Zone,River,Station,Dates,Sample No,5-Day Biochemical Oxygen Demand (mg/L),Ammonia-Nitrogen (mg/L),Aluminium (μg/L),Anionic Surfactants (as Manoxol OT) (mg/L),Arsenic (μg/L),...,Fluoride (mg/L),Flow (m³/s),Faecal Coliforms (counts/100mL),Dissolved Oxygen (mg/L),Dissolved Oxygen (%saturation),Cyanide (mg/L),Copper (μg/L),Chlorophyll-a (μg/L),E. coli (counts/100mL),Silica (as SiO2) (mg/L)
0,Tolo Harbour and Channel,Siu Lek Yuen Nullah,TR23A,1986-01-29,1,75,3.3,100,NaN,1,...,NaN,NaN,NaN,4.9,63.0,NaN,7,NaN,NaN,NaN
1,Tolo Harbour and Channel,Siu Lek Yuen Nullah,TR23A,1986-02-25,1,27.8,1.7,20,NaN,1,...,NaN,NaN,NaN,2.6,28.0,NaN,1,NaN,NaN,NaN
2,Tolo Harbour and Channel,Siu Lek Yuen Nullah,TR23A,1986-03-25,1,21.8,3.9,NaN,NaN,NaN,...,NaN,NaN,NaN,3.0,33.0,0.01,NaN,NaN,NaN,NaN
3,Tolo Harbour and Channel,Siu Lek Yuen Nullah,TR23A,1986-04-21,1,6.3,0.017,470,0.05,1,...,0.3,NaN,NaN,8.3,95.0,NaN,5,NaN,NaN,NaN
4,Tolo Harbour and Channel,Siu Lek Yuen Nullah,TR23A,1986-05-29,1,17.4,0.55,150,0.07,1,...,0.6,NaN,NaN,8.3,112.0,NaN,2,NaN,NaN,NaN

In [ ]:
Hong_Kong_River_Water_Quality_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35196 entries, 0 to 35195
Data columns (total 56 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Water Control Zone                          35196 non-null  object
 1   River                                       35196 non-null  object
 2   Station                                     35196 non-null  object
 3   Dates                                       35196 non-null  object
 4   Sample No                                   35196 non-null  int64
 5   5-Day Biochemical Oxygen Demand (mg/L)      35080 non-null  object
 6   Ammonia-Nitrogen (mg/L)                     35189 non-null  object
 7   Aluminium (μg/L)                            35027 non-null  object
 8   Anionic Surfactants (as Manoxol OT) (mg/L)  35043 non-null  object
 9   Arsenic (μg/L)                              35062 non-null  object
 10  Barium (μg/L)                               28102 non-null  object
 11  Antimony (μg/L)                             27745 non-null  object
 12  Beryllium (μg/L)                            25485 non-null  object
 13  Boron (μg/L)                                35027 non-null  object
 14  Cadmium (μg/L)                              35061 non-null  object
 15  Chemical Oxygen Demand (mg/L)               35184 non-null  object
 16  Chloride (mg/L)                             32195 non-null  object
 17  Chlorophyll-𝘢 (μg/L)                        18375 non-null  object
 18  Conductivity (μS/cm)                        35191 non-null  float64
 19  Chromium (μg/L)                             35062 non-null  object
 20  𝐸. 𝑐𝑜𝑙𝑖  (counts/100mL)                     28694 non-null  object
 21  Zinc (μg/L)                                 35061 non-null  object
 22  Water Temperature (°C)                      35187 non-null  float64
 23  Vanadium (μg/L)                             28102 non-null  object
 24  Turbidity (NTU)                             35184 non-null  float64
 25  Total Volatile Solids (mg/L)                35053 non-null  object
 26  Total Solids (mg/L)                         35053 non-null  object
 27  Total Phosphorus (mg/L)                     34692 non-null  object
 28  Total Organic Carbon (mg/L)                 35016 non-null  object
 29  Total Kjeldahl Nitrogen (mg/L)              34691 non-null  object
 30  Thallium (μg/L)                             25485 non-null  object
 31  Suspended solids (mg/L)                     35185 non-null  object
 32  Sulphide (mg/L)                             34825 non-null  object
 33  Silver (μg/L)                               28176 non-null  object
 34  Silica (as SiO₂) (mg/L)                     35189 non-null  object
 35  Salinity (psu)                              27377 non-null  float64
 36  Phaeopigment (μg/L)                         18335 non-null  object
 37  pH                                          35184 non-null  float64
 38  Orthophosphate Phosphorus (mg/L)            35189 non-null  object
 39  Oil and Grease (mg/L)                       35072 non-null  object
 40  Nitrite-Nitrogen (mg/L)                     35189 non-null  object
 41  Nitrate-Nitrogen (mg/L)                     35189 non-null  object
 42  Nickel (μg/L)                               34692 non-null  object
 43  Molybdenum (μg/L)                           25485 non-null  object
 44  Mercury (μg/L)                              34901 non-null  object
 45  Manganese (μg/L)                            34995 non-null  object
 46  Lead (μg/L)                                 35061 non-null  object
 47  Iron (μg/L)                                 34887 non-null  object
 48  Free Hydrogen Sulphide (mg/L)               34883 non-null  object
 49  Fluoride (mg/L)                             35019 non-null  object
 50  Flow (m³/s)                                 22981 non-null  float64
 51  Faecal Coliforms (counts/100mL)             28693 non-null  object
 52  Dissolved Oxygen (mg/L)                     35192 non-null  float64
 53  Dissolved Oxygen (%saturation)              35192 non-null  float64
 54  Cyanide (mg/L)                              34987 non-null  object
 55  Copper (μg/L)                               35061 non-null  object
dtypes: float64(8), int64(1), object(47)
memory usage: 15.0+ MB

In [ ]:
# Save the combined dataset into a single CSV file

data_columns = ["Water Control Zone", "River", "Station", "Dates", "Sample No",
               "5-Day Biochemical Oxygen Demand (mg/L)", "Ammonia-Nitrogen (mg/L)",
               "Aluminium (μg/L)", "Anionic Surfactants (as Manoxol OT) (mg/L)",
               "Arsenic (μg/L)", "Barium (μg/L)", "Antimony (μg/L)",
               "Beryllium (μg/L)", "Boron (μg/L)", "Cadmium (μg/L)",
               "Chemical Oxygen Demand (mg/L)", "Chloride (mg/L)",
               "Chlorophyll-a (μg/L)", "Conductivity (μS/cm)", "Chromium (μg/L)",
               "E. coli (counts/100mL)", "Zinc (μg/L)", "Water Temperature (°C)",
               "Vanadium (μg/L)", "Turbidity (NTU)", "Total Volatile Solids (mg/L)",
               "Total Solids (mg/L)", "Total Phosphorus (mg/L)",
               "Total Organic Carbon (mg/L)", "Total Kjeldahl Nitrogen (mg/L)",
               "Thallium (μg/L)", "Suspended solids (mg/L)", "Sulphide (mg/L)",
               "Silver (μg/L)", "Silica (as SiO2) (mg/L)", "Salinity (psu)",
               "Phaeopigment (μg/L)", "pH", "Orthophosphate Phosphorus (mg/L)",
               "Oil and Grease (mg/L)", "Nitrite-Nitrogen (mg/L)",
               "Nitrate-Nitrogen (mg/L)", "Nickel (μg/L)", "Molybdenum (μg/L)",
               "Mercury (μg/L)", "Manganese (μg/L)", "Lead (μg/L)",
               "Iron (μg/L)", "Free Hydrogen Sulphide (mg/L)", "Fluoride (mg/L)",
               "Flow (m³/s)", "Faecal Coliforms (counts/100mL)", "Dissolved Oxygen (mg/L)",
               "Dissolved Oxygen (%saturation)", "Cyanide (mg/L)", "Copper (μg/L)"]

Hong_Kong_River_Water_Quality_df.columns = data_columns

Hong_Kong_River_Water_Quality_df.to_csv(os.path.join(hong_kong_data_dir, "hong_kong_river_water_quality_combined.csv"), index=False)

In [ ]:
Hong_Kong_River_Water_Quality_coordinates_df = pd.read_csv(os.path.join(hong_kong_data_dir, "hong_kong_river_water_quality_combined_coordinates.csv"))
Hong_Kong_River_Water_Quality_coordinates_df.head()

,Water Control Zone,Watercourse,Station,Latitude,Longitude
0,Tolo Harbour and Channel,Shing Mun River,KY1,"22° 21' 39.8"" N","114° 12' 32.0"" E"
1,Tolo Harbour and Channel,Shing Mun River,TR17,"22° 23' 47.5"" N","114° 11' 41.4"" E"
2,Tolo Harbour and Channel,Shing Mun River,TR17L,"22° 23' 31.5"" N","114° 12' 00.0"" E"
3,Tolo Harbour and Channel,Shing Mun River,TR19,"22° 22' 30.3"" N","114° 10' 50.0"" E"
4,Tolo Harbour and Channel,Shing Mun River,TR19A,"22° 22' 38.0"" N","114° 10' 18.8"" E"

In [49]:
# Helper function to convert DMS to Degrees
import re

def dms_to_decimal(dms):
    # Extract numbers
    parts = re.findall(r"\d+\.?\d*", dms)
    degrees, minutes, seconds = map(float, parts)

    decimal = degrees + minutes / 60 + seconds / 3600

    # Handle direction
    if any(x in dms for x in ["S", "W"]):
        decimal = -decimal

    return decimal

In [ ]:
# Apply DMS to Decimal conversion
Hong_Kong_River_Water_Quality_coordinates_df["Latitude"] = Hong_Kong_River_Water_Quality_coordinates_df["Latitude"].apply(dms_to_decimal)
Hong_Kong_River_Water_Quality_coordinates_df["Longitude"] = Hong_Kong_River_Water_Quality_coordinates_df["Longitude"].apply(dms_to_decimal)

In [ ]:
Hong_Kong_River_Water_Quality_coordinates_df.head()

         Water Control Zone      Watercourse Station   Latitude   Longitude
0  Tolo Harbour and Channel  Shing Mun River     KY1  22.361056  114.208889
1  Tolo Harbour and Channel  Shing Mun River    TR17  22.396528  114.194833
2  Tolo Harbour and Channel  Shing Mun River  TR17L   22.392083  114.200000
3  Tolo Harbour and Channel  Shing Mun River   TR19   22.375083  114.180556
4  Tolo Harbour and Channel  Shing Mun River  TR19A   22.377222  114.171889

In [ ]:
Hong_Kong_River_Water_Quality_coordinates_df = Hong_Kong_River_Water_Quality_coordinates_df.rename(columns={"Watercourse": "River"})

In [ ]:
# Load combined dataset
Hong_Kong_River_Water_Quality_df = pd.read_csv(os.path.join(hong_kong_data_dir, "hong_kong_river_water_quality_combined.csv"))
Hong_Kong_River_Water_Quality_df.head()

/var/folders/n2/km_1mc9n48g26dqmvhjr0w8m0000gn/T/ipykernel_80632/747767069.py:2: DtypeWarning: Columns (25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  Hong_Kong_River_Quality_df = pd.read_csv(os.path.join(data_dir, "hong_kong_river_quality_combined.csv"))

,Water Control Zone,River,Station,Dates,Sample No,5-Day Biochemical Oxygen Demand (mg/L),Ammonia-Nitrogen (mg/L),Aluminium (μg/L),Anionic Surfactants (as Manoxol OT) (mg/L),Arsenic (μg/L),...,Lead (μg/L),Iron (μg/L),Free Hydrogen Sulphide (mg/L),Fluoride (mg/L),Flow (m³/s),Faecal Coliforms (counts/100mL),Dissolved Oxygen (mg/L),Dissolved Oxygen (%saturation),Cyanide (mg/L),Copper (μg/L)
0,Tolo Harbour and Channel,Siu Lek Yuen Nullah,TR23A,29/01/1986,1,75,3.3,100,NaN,1,...,2,NaN,NaN,NaN,NaN,NaN,4.9,63.0,NaN,7
1,Tolo Harbour and Channel,Siu Lek Yuen Nullah,TR23A,25/02/1986,1,27.8,1.7,20,NaN,1,...,1,NaN,NaN,NaN,NaN,NaN,2.6,28.0,NaN,1
2,Tolo Harbour and Channel,Siu Lek Yuen Nullah,TR23A,25/03/1986,1,21.8,3.9,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,33.0,0.01,NaN
3,Tolo Harbour and Channel,Siu Lek Yuen Nullah,TR23A,21/04/1986,1,6.3,0.017,470,0.05,1,...,10,NaN,NaN,0.3,NaN,NaN,8.3,95.0,NaN,5
4,Tolo Harbour and Channel,Siu Lek Yuen Nullah,TR23A,29/05/1986,1,17.4,0.55,150,0.07,1,...,1,NaN,NaN,0.6,NaN,NaN,8.3,112.0,NaN,2

In [ ]:
# Remove extra whitespaces from "Station" column
Hong_Kong_River_Water_Quality_df["Station"] = Hong_Kong_River_Water_Quality_df["Station"].str.strip()
Hong_Kong_River_Water_Quality_coordinates_df["Station"] = Hong_Kong_River_Water_Quality_coordinates_df["Station"].str.strip()

In [ ]:
# Map coordinates to the main dataset
Hong_Kong_River_Water_Quality_merged_df = Hong_Kong_River_Water_Quality_df.merge(
    Hong_Kong_River_Water_Quality_coordinates_df[["Station", "Latitude", "Longitude"]],
    on=["Station"],
    how="left"
)

In [ ]:
Hong_Kong_River_Water_Quality_merged_df.head()

,Water Control Zone,River,Station,Dates,Sample No,5-Day Biochemical Oxygen Demand (mg/L),Ammonia-Nitrogen (mg/L),Aluminium (μg/L),Anionic Surfactants (as Manoxol OT) (mg/L),Arsenic (μg/L),...,Free Hydrogen Sulphide (mg/L),Fluoride (mg/L),Flow (m³/s),Faecal Coliforms (counts/100mL),Dissolved Oxygen (mg/L),Dissolved Oxygen (%saturation),Cyanide (mg/L),Copper (μg/L),Latitude,Longitude
0,Tolo Harbour and Channel,Siu Lek Yuen Nullah,TR23A,29/01/1986,1,75,3.3,100,NaN,1,...,NaN,NaN,NaN,NaN,4.9,63.0,NaN,7,22.383917,114.21025
1,Tolo Harbour and Channel,Siu Lek Yuen Nullah,TR23A,25/02/1986,1,27.8,1.7,20,NaN,1,...,NaN,NaN,NaN,NaN,2.6,28.0,NaN,1,22.383917,114.21025
2,Tolo Harbour and Channel,Siu Lek Yuen Nullah,TR23A,25/03/1986,1,21.8,3.9,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.0,33.0,0.01,NaN,22.383917,114.21025
3,Tolo Harbour and Channel,Siu Lek Yuen Nullah,TR23A,21/04/1986,1,6.3,0.017,470,0.05,1,...,NaN,0.3,NaN,NaN,8.3,95.0,NaN,5,22.383917,114.21025
4,Tolo Harbour and Channel,Siu Lek Yuen Nullah,TR23A,29/05/1986,1,17.4,0.55,150,0.07,1,...,NaN,0.6,NaN,NaN,8.3,112.0,NaN,2,22.383917,114.21025

In [ ]:
# Save the merged dataset
Hong_Kong_River_Water_Quality_merged_df.to_csv(os.path.join(data_dir, "hong_kong_river_water_quality_merged_combined.csv"), index=False)

 ## 🗂️ **Preparing Data - Combining Dataset & Merging Coordinates England**

In [41]:
england_data_dir = os.path.join(base_dir, "data", "England")

if not os.path.exists(england_data_dir):
    raise FileNotFoundError("England data directory not found.")

In [ ]:
England_River_Water_Quality_coordinates_df = pd.read_csv(os.path.join(england_data_dir, "sitelocations_2009_2023.csv"))
England_River_Water_Quality_coordinates_df.head()

,Code,River: Site name,Latitude,Longitude,Nearest relevant flow gauging station,National River Flow Archive gauging station ID number
0,Tm,Thame at Wheatley,51.740372,-1.115066,Thame at Wheatley gauging station,39105
1,Ra,Ray at Islip,51.821247,-1.236807,Ray at Islip gauging station,39140
2,Ch,Cherwell at Hampton Poyle,51.833191,-1.277240,Cherwell at Enslow Mill gauging station,39021
3,Ev,Evenlode at Cassington Mill,51.787779,-1.353355,Evenlode at Cassington gauging station,39034
4,TS,Thames at Swinford,51.773434,-1.360806,Thames at Eynesham gauging station,39008

In [ ]:
England_River_Water_Quality_coordinates_df = England_River_Water_Quality_coordinates_df.rename(columns={"River: Site name": "River"})

In [ ]:
England_River_Water_Quality_coordinates_df.head()

,Code,River,Latitude,Longitude,Nearest relevant flow gauging station,National River Flow Archive gauging station ID number
0,Tm,Thame at Wheatley,51.740372,-1.115066,Thame at Wheatley gauging station,39105
1,Ra,Ray at Islip,51.821247,-1.236807,Ray at Islip gauging station,39140
2,Ch,Cherwell at Hampton Poyle,51.833191,-1.277240,Cherwell at Enslow Mill gauging station,39021
3,Ev,Evenlode at Cassington Mill,51.787779,-1.353355,Evenlode at Cassington gauging station,39034
4,TS,Thames at Swinford,51.773434,-1.360806,Thames at Eynesham gauging station,39008

In [ ]:
# Load combined dataset
England_River_Water_Quality_df = pd.read_csv(os.path.join(england_data_dir, "thamesinitiativewaterquality_2009_2023.csv"), encoding="latin1")
England_River_Water_Quality_df = England_River_Water_Quality_df.rename(columns={"Site_name": "River"})
England_River_Water_Quality_df.head()

,Sample_ID,Date,River,Time,Water_Temperature (oC),Lab_pH,Gran_alkalinity_µeq/L,Suspended_solids_mg/L,Soluble_reactive_phosphorus_(µg P/L),Total_dissolved_phosphorus_(µg _P/L),...,Dissolved_Cu_(µg/L),Total_Na_(mg/L),Total_Ca_(mg/L),Total_Mg_(mg/L),Total_B_(µg/L),Total_Fe_(µg/L),Total_Mn_(µg/L),Total_Zn_(µg/L),Total_Cu_(µg/L),Total_Al_(µg/L)
0,TC1,16/02/2009,Thame at Wheatley,09:45,NaN,7.86,4558,10.9,170,188,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TC1,03/03/2009,Thame at Wheatley,09:30,7.2,8.01,4915,7.7,351,375,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,TC1,09/03/2009,Thame at Wheatley,09:45,6.8,7.94,5637,7.5,280,292,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,TC1,16/03/2009,Thame at Wheatley,10:00,9.3,8.05,5393,5.3,322,364,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,TC1,24/03/2009,Thame at Wheatley,09:45,7.8,8.14,5351,6,312,336,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Remove extra whitespaces from 'River' column
England_River_Water_Quality_coordinates_df["River"] = England_River_Water_Quality_coordinates_df["River"].str.strip()
England_River_Water_Quality_df["River"] = England_River_Water_Quality_df["River"].str.strip()

In [ ]:
# Standardise river names
England_River_Water_Quality_df.loc[England_River_Water_Quality_df["River"] == "Jubilee River at Datchet", "River"] = "Jubilee River at Pococks Bridge"

In [ ]:
# Map coordinates to the main dataset
England_River_Water_Quality_merged_df = England_River_Water_Quality_df.merge(
    England_River_Water_Quality_coordinates_df[["River", "Latitude", "Longitude"]],
    on=["River"],
    how="left"
)

In [ ]:
England_River_Water_Quality_merged_df.head()

,Sample_ID,Date,River,Time,Water_Temperature (oC),Lab_pH,Gran_alkalinity_µeq/L,Suspended_solids_mg/L,Soluble_reactive_phosphorus_(µg P/L),Total_dissolved_phosphorus_(µg _P/L),...,Total_Ca_(mg/L),Total_Mg_(mg/L),Total_B_(µg/L),Total_Fe_(µg/L),Total_Mn_(µg/L),Total_Zn_(µg/L),Total_Cu_(µg/L),Total_Al_(µg/L),Latitude,Longitude
0,TC1,16/02/2009,Thame at Wheatley,09:45,NaN,7.86,4558,10.9,170,188,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.740372,-1.115066
1,TC1,03/03/2009,Thame at Wheatley,09:30,7.2,8.01,4915,7.7,351,375,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.740372,-1.115066
2,TC1,09/03/2009,Thame at Wheatley,09:45,6.8,7.94,5637,7.5,280,292,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.740372,-1.115066
3,TC1,16/03/2009,Thame at Wheatley,10:00,9.3,8.05,5393,5.3,322,364,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.740372,-1.115066
4,TC1,24/03/2009,Thame at Wheatley,09:45,7.8,8.14,5351,6,312,336,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.740372,-1.115066

In [ ]:
# Save the merged dataset
England_River_Water_Quality_merged_df.to_csv(os.path.join(data_dir, "england_river_water_quality_merged_combined.csv"), index=False)

 ## 🗂️ **Preparing Data - Combining Dataset England & Hong Kong**

In [304]:
import os
import pandas as pd

In [305]:
base_dir = base_dir = os.path.dirname(os.getcwd())
data_dir = os.path.join(base_dir, "data")

In [ ]:
Hong_Kong_River_Water_Quality_merged_df = pd.read_csv(os.path.join(data_dir, "hong_kong_river_water_quality_merged_combined.csv"))
Hong_Kong_River_Water_Quality_merged_df.head()

/var/folders/n2/km_1mc9n48g26dqmvhjr0w8m0000gn/T/ipykernel_71270/746639490.py:1: DtypeWarning: Columns (25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  Hong_Kong_River_Quality_merged_df = pd.read_csv(os.path.join(data_dir, "hong_kong_river_quality_merged_combined.csv"))

,Water Control Zone,River,Station,Dates,Sample No,5-Day Biochemical Oxygen Demand (mg/L),Ammonia-Nitrogen (mg/L),Aluminium (μg/L),Anionic Surfactants (as Manoxol OT) (mg/L),Arsenic (μg/L),...,Free Hydrogen Sulphide (mg/L),Fluoride (mg/L),Flow (m³/s),Faecal Coliforms (counts/100mL),Dissolved Oxygen (mg/L),Dissolved Oxygen (%saturation),Cyanide (mg/L),Copper (μg/L),Latitude,Longitude
0,Tolo Harbour and Channel,Siu Lek Yuen Nullah,TR23A,29/01/1986,1,75,3.3,100,NaN,1,...,NaN,NaN,NaN,NaN,4.9,63.0,NaN,7,22.383917,114.21025
1,Tolo Harbour and Channel,Siu Lek Yuen Nullah,TR23A,25/02/1986,1,27.8,1.7,20,NaN,1,...,NaN,NaN,NaN,NaN,2.6,28.0,NaN,1,22.383917,114.21025
2,Tolo Harbour and Channel,Siu Lek Yuen Nullah,TR23A,25/03/1986,1,21.8,3.9,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.0,33.0,0.01,NaN,22.383917,114.21025
3,Tolo Harbour and Channel,Siu Lek Yuen Nullah,TR23A,21/04/1986,1,6.3,0.017,470,0.05,1,...,NaN,0.3,NaN,NaN,8.3,95.0,NaN,5,22.383917,114.21025
4,Tolo Harbour and Channel,Siu Lek Yuen Nullah,TR23A,29/05/1986,1,17.4,0.55,150,0.07,1,...,NaN,0.6,NaN,NaN,8.3,112.0,NaN,2,22.383917,114.21025

In [ ]:
# Rename columns for consistency
Hong_Kong_River_Water_Quality_merged_df.columns = Hong_Kong_River_Water_Quality_merged_df.columns.str.replace("Œº", "µ", regex=False).str.replace("μ", "µ", regex=False).str.replace("Œº", "µ", regex=False).str.strip()

Hong_Kong_River_Water_Quality_merged_df = Hong_Kong_River_Water_Quality_merged_df.rename(columns={
    "Conductivity (µS/cm)": "EC",
    "Water Temperature (°C)": "Temp_C",
    "Suspended solids (mg/L)": "SS_mgL",
    "Total Phosphorus (mg/L)": "TP_mgL",
    "Nitrite-Nitrogen (mg/L)": "NO2_N_mgL",
    "Nitrate-Nitrogen (mg/L)": "NO3_N_mgL",
    "Dissolved Oxygen (mg/L)": "DO_mgL"
})

Hong_Kong_River_Water_Quality_merged_df = Hong_Kong_River_Water_Quality_merged_df.rename(columns={
    "Aluminium (µg/L)": "Al_ugL",
    "Zinc (µg/L)": "Zn_ugL",
    "Manganese (µg/L)": "Mn_ugL",
    "Iron (µg/L)": "Fe_ugL",
    "Copper (µg/L)": "Cu_ugL",
    "Chlorophyll-a (µg/L)": "Chl_a_ugL"
})

Hong_Kong_River_Water_Quality_merged_df = Hong_Kong_River_Water_Quality_merged_df.rename(columns={
    "River": "River",
    "Dates": "Date",
    "Latitude": "Latitude",
    "Longitude": "Longitude",
    "pH": "pH"
})

In [ ]:
Hong_Kong_River_Water_Quality_merged_df.columns.tolist()

['Water Control Zone',
 'River',
 'Station',
 'Date',
 'Sample No',
 '5-Day Biochemical Oxygen Demand (mg/L)',
 'Ammonia-Nitrogen (mg/L)',
 'Al_ugL',
 'Anionic Surfactants (as Manoxol OT) (mg/L)',
 'Arsenic (µg/L)',
 'Barium (µg/L)',
 'Antimony (µg/L)',
 'Beryllium (µg/L)',
 'Boron (µg/L)',
 'Cadmium (µg/L)',
 'Chemical Oxygen Demand (mg/L)',
 'Chloride (mg/L)',
 'Chl_a_ugL',
 'EC',
 'Chromium (µg/L)',
 'E. coli (counts/100mL)',
 'Zn_ugL',
 'Temp_C',
 'Vanadium (µg/L)',
 'Turbidity (NTU)',
 'Total Volatile Solids (mg/L)',
 'Total Solids (mg/L)',
 'TP_mgL',
 'Total Organic Carbon (mg/L)',
 'Total Kjeldahl Nitrogen (mg/L)',
 'Thallium (µg/L)',
 'SS_mgL',
 'Sulphide (mg/L)',
 'Silver (µg/L)',
 'Silica (as SiO2) (mg/L)',
 'Salinity (psu)',
 'Phaeopigment (µg/L)',
 'pH',
 'Orthophosphate Phosphorus (mg/L)',
 'Oil and Grease (mg/L)',
 'NO2_N_mgL',
 'NO3_N_mgL',
 'Nickel (µg/L)',
 'Molybdenum (µg/L)',
 'Mercury (µg/L)',
 'Mn_ugL',
 'Lead (µg/L)',
 'Fe_ugL',
 'Free Hydrogen Sulphide (mg/L)',
 'Fluoride (mg/L)',
 'Flow (m³/s)',
 'Faecal Coliforms (counts/100mL)',
 'DO_mgL',
 'Dissolved Oxygen (%saturation)',
 'Cyanide (mg/L)',
 'Cu_ugL',
 'Latitude',
 'Longitude']

In [ ]:
hong_kong_cols_to_keep =  ["River", "Date", "Latitude", "Longitude",
                           "EC", "Temp_C", "SS_mgL", "pH",
                           "TP_mgL", "NO2_N_mgL", "NO3_N_mgL", "DO_mgL",
                           "Al_ugL", "Zn_ugL", "Mn_ugL", "Fe_ugL", 
                           "Cu_ugL", "Chl_a_ugL"]



Hong_Kong_River_Water_Quality_merged_df = Hong_Kong_River_Water_Quality_merged_df[[col for col in hong_kong_cols_to_keep if col in Hong_Kong_River_Water_Quality_merged_df.columns]]

In [ ]:
Hong_Kong_River_Water_Quality_merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35196 entries, 0 to 35195
Data columns (total 18 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   River      35196 non-null  object
 1   Date       35196 non-null  object
 2   Latitude   35196 non-null  float64
 3   Longitude  35196 non-null  float64
 4   EC         35191 non-null  float64
 5   Temp_C     35187 non-null  float64
 6   SS_mgL     35185 non-null  object
 7   pH         35184 non-null  float64
 8   TP_mgL     34692 non-null  object
 9   NO2_N_mgL  35189 non-null  object
 10  NO3_N_mgL  35189 non-null  object
 11  DO_mgL     35192 non-null  float64
 12  Al_ugL     35027 non-null  object
 13  Zn_ugL     35061 non-null  object
 14  Mn_ugL     34995 non-null  object
 15  Fe_ugL     34887 non-null  object
 16  Cu_ugL     35061 non-null  object
 17  Chl_a_ugL  18375 non-null  object
dtypes: float64(6), object(12)
memory usage: 4.8+ MB

In [ ]:
Hong_Kong_River_Water_Quality_merged_df.head(100)

,River,Date,Latitude,Longitude,EC,Temp_C,SS_mgL,pH,TP_mgL,NO2_N_mgL,NO3_N_mgL,DO_mgL,Al_ugL,Zn_ugL,Mn_ugL,Fe_ugL,Cu_ugL,Chl_a_ugL
0,Siu Lek Yuen Nullah,29/01/1986,22.383917,114.21025,7250.0,19.9,28,7.4,2.8,0.004,1.8,4.9,100,50,NaN,NaN,7,NaN
1,Siu Lek Yuen Nullah,25/02/1986,22.383917,114.21025,22000.0,16.9,11,7.4,0.86,0.064,0.2,2.6,20,10,NaN,NaN,1,NaN
2,Siu Lek Yuen Nullah,25/03/1986,22.383917,114.21025,9600.0,16.6,23,7.3,1.5,0.15,0.88,3.0,NaN,NaN,NaN,NaN,NaN,NaN
3,Siu Lek Yuen Nullah,21/04/1986,22.383917,114.21025,2500.0,21.5,150,7.3,0.35,0.14,2.2,8.3,470,40,170,NaN,5,NaN
4,Siu Lek Yuen Nullah,29/05/1986,22.383917,114.21025,22000.0,28.4,25,8.3,0.43,0.017,0.37,8.3,150,20,150,NaN,2,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Siu Lek Yuen Nullah,24/01/1994,22.383917,114.21025,3700.0,13.3,3.1,7.1,0.26,0.053,0.967,8.7,60,20,90,110,1,NaN
96,Siu Lek Yuen Nullah,21/02/1994,22.383917,114.21025,3370.0,15.8,3.7,7.4,0.3,0.051,0.941,7.2,100,20,130,130,2,NaN
97,Siu Lek Yuen Nullah,21/03/1994,22.383917,114.21025,25060.0,17.4,3.6,7.8,0.28,0.045,0.585,6.1,120,30,90,90,2,NaN
98,Siu Lek Yuen Nullah,21/04/1994,22.383917,114.21025,42720.0,23.7,27,8.2,0.29,0.022,0.187,4.8,180,40,130,290,1,NaN
99,Siu Lek Yuen Nullah,23/05/1994,22.383917,114.21025,27550.0,28.7,9.8,8.4,0.36,<0.002,0.009,7.6,60,<10,120,80,<1,NaN

In [ ]:
England_River_Water_Quality_merged_df = pd.read_csv(os.path.join(data_dir, "england_river_water_quality_merged_combined.csv"))
England_River_Water_Quality_merged_df.head()

,Sample_ID,Date,River,Time,Water_Temperature (oC),Lab_pH,Gran_alkalinity_µeq/L,Suspended_solids_mg/L,Soluble_reactive_phosphorus_(µg P/L),Total_dissolved_phosphorus_(µg _P/L),...,Total_Ca_(mg/L),Total_Mg_(mg/L),Total_B_(µg/L),Total_Fe_(µg/L),Total_Mn_(µg/L),Total_Zn_(µg/L),Total_Cu_(µg/L),Total_Al_(µg/L),Latitude,Longitude
0,TC1,16/02/2009,Thame at Wheatley,09:45,NaN,7.86,4558,10.9,170,188,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.740372,-1.115066
1,TC1,03/03/2009,Thame at Wheatley,09:30,7.2,8.01,4915,7.7,351,375,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.740372,-1.115066
2,TC1,09/03/2009,Thame at Wheatley,09:45,6.8,7.94,5637,7.5,280,292,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.740372,-1.115066
3,TC1,16/03/2009,Thame at Wheatley,10:00,9.3,8.05,5393,5.3,322,364,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.740372,-1.115066
4,TC1,24/03/2009,Thame at Wheatley,09:45,7.8,8.14,5351,6,312,336,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.740372,-1.115066

In [ ]:
England_River_Water_Quality_merged_df.columns = (England_River_Water_Quality_merged_df.columns.str.replace("¬µ", "µ", regex=False).str.replace("μ", "µ", regex=False).str.strip())

England_River_Water_Quality_merged_df = England_River_Water_Quality_merged_df.rename(columns={
    "Water_Temperature (oC)": "Temp_C",
    "Field_pH": "pH",
    "Suspended_solids_mg/L": "SS_mgL",
    "Total_phosphorus_(µg P/L)": "TP_ugL",
    "Dissolved_nitrite_(mg_NO2/L)": "NO2_mgL",
    "Dissolved_nitrate_(mg_NO3/L)": "NO3_mgL",
    "Conductivity_(µS/cm)": "EC",
    "Dissolved_oxygen_(mg/L)": "DO_mgL"
})

England_River_Water_Quality_merged_df = England_River_Water_Quality_merged_df.rename(columns=lambda x: "Chl_a_ugL" if "Chlorophyll-a" in x else x)

England_River_Water_Quality_merged_df = England_River_Water_Quality_merged_df.rename(columns={
    "Dissolved_Al_(mg/L)": "Al_mgL",
    "Dissolved_Fe_(µg/L)": "Fe_ugL",
    "Dissolved_Mn_(µg/L)": "Mn_ugL",
    "Dissolved_Zn_(µg/L)": "Zn_ugL",
    "Dissolved_Cu_(µg/L)": "Cu_ugL"
})

In [ ]:
England_River_Water_Quality_merged_df.columns.tolist()

['Sample_ID',
 'Date',
 'River',
 'Time',
 'Temp_C',
 'Lab_pH',
 'Gran_alkalinity_µeq/L',
 'SS_mgL',
 'Soluble_reactive_phosphorus_(µg P/L)',
 'Total_dissolved_phosphorus_(µg _P/L)',
 'TP_ugL',
 'Dissolved_ammonium_(mg NH4/l)',
 'Dissolved_silicon_(mg_Si/L)',
 'Chl_a_ugL',
 'Dissolved_fluoride_(mg_F/L)',
 'Dissolved_chloride_(mg_Cl/L)',
 'NO2_mgL',
 'NO3_mgL',
 'Dissolved_sulphate_(mg_SO4/L)',
 'Total_dissolved_nitrogen_(mg_N/L)',
 'Dissolved_organic_carbon_(mg/L)',
 'pH',
 'EC',
 'Redox_potential_(mV)',
 'Dissolved_oxygen_(%_saturation)',
 'DO_mgL',
 'Al_mgL',
 'Dissolved_B_(µg/L)',
 'Dissolved_Ca_(mg/L)',
 'Fe_ugL',
 'Dissolved_K_(mg/L)',
 'Dissolved_Mg_(mg/L)',
 'Dissolved_Na_(mg/L)',
 'Dissolved_P_(mg/L)',
 'Dissolved_S_(mg/L)',
 'Dissolved_Si_(mg/L)',
 'Mn_ugL',
 'Zn_ugL',
 'Cu_ugL',
 'Total_Na_(mg/L)',
 'Total_Ca_(mg/L)',
 'Total_Mg_(mg/L)',
 'Total_B_(µg/L)',
 'Total_Fe_(µg/L)',
 'Total_Mn_(µg/L)',
 'Total_Zn_(µg/L)',
 'Total_Cu_(µg/L)',
 'Total_Al_(µg/L)',
 'Latitude',
 'Longitude']

In [ ]:
england_cols_to_keep = ["River", "Date", "Latitude", "Longitude",
                        "EC", "Temp_C", "SS_mgL", "pH",
                        "TP_ugL", "NO2_mgL", "NO3_mgL", "DO_mgL", 
                        "Al_mgL", "Zn_ugL", "Mn_ugL", "Fe_ugL",
                        "Cu_ugL", "Chl_a_ugL"]

England_River_Water_Quality_merged_df = England_River_Water_Quality_merged_df[[col for col in england_cols_to_keep if col in England_River_Water_Quality_merged_df.columns]]

In [ ]:
England_River_Water_Quality_merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13203 entries, 0 to 13202
Data columns (total 18 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   River      13203 non-null  object
 1   Date       13203 non-null  object
 2   Latitude   13203 non-null  float64
 3   Longitude  13203 non-null  float64
 4   EC         8422 non-null   float64
 5   Temp_C     12606 non-null  object
 6   SS_mgL     12699 non-null  object
 7   pH         8359 non-null   float64
 8   TP_ugL     13203 non-null  object
 9   NO2_mgL    13203 non-null  object
 10  NO3_mgL    13203 non-null  object
 11  DO_mgL     2534 non-null   float64
 12  Al_mgL     6480 non-null   object
 13  Zn_ugL     6550 non-null   float64
 14  Mn_ugL     6550 non-null   float64
 15  Fe_ugL     6804 non-null   object
 16  Cu_ugL     6550 non-null   float64
 17  Chl_a_ugL  13153 non-null  object
dtypes: float64(8), object(10)
memory usage: 1.8+ MB

In [ ]:
import numpy as np
import pandas as pd

# Helper function to clean numeric values
def clean_numeric(val):
    if pd.isna(val):
        return np.nan
    
    val = str(val).strip().upper()
    
    if val in ["ND", "LOD", "BDL", "-", "", "NA"]:
        return np.nan
    
    if val.startswith("<"):
        try:
            return float(val.replace("<", "")) / 2
        except:
            return np.nan
    
    val = val.replace(",", "")
    
    try:
        return float(val)
    except:
        return np.nan

In [ ]:
for col in Hong_Kong_River_Water_Quality_merged_df.columns:
    if Hong_Kong_River_Water_Quality_merged_df[col].dtype == "object" and col not in ["River", "Date"]:
        Hong_Kong_River_Water_Quality_merged_df[col] = Hong_Kong_River_Water_Quality_merged_df[col].apply(clean_numeric)

In [ ]:
Hong_Kong_River_Water_Quality_merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35196 entries, 0 to 35195
Data columns (total 18 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   River      35196 non-null  object
 1   Date       35196 non-null  object
 2   Latitude   35196 non-null  float64
 3   Longitude  35196 non-null  float64
 4   EC         35191 non-null  float64
 5   Temp_C     35187 non-null  float64
 6   SS_mgL     35185 non-null  float64
 7   pH         35184 non-null  float64
 8   TP_mgL     34692 non-null  float64
 9   NO2_N_mgL  35189 non-null  float64
 10  NO3_N_mgL  35189 non-null  float64
 11  DO_mgL     35192 non-null  float64
 12  Al_ugL     35027 non-null  float64
 13  Zn_ugL     35061 non-null  float64
 14  Mn_ugL     34995 non-null  float64
 15  Fe_ugL     34877 non-null  float64
 16  Cu_ugL     35061 non-null  float64
 17  Chl_a_ugL  18375 non-null  float64
dtypes: float64(16), object(2)
memory usage: 4.8+ MB

In [ ]:
ug_cols = ["Al_ugL", "Fe_ugL", "Mn_ugL", "Zn_ugL", "Cu_ugL", "Chl_a_ugL"]

for col in ug_cols:
    Hong_Kong_River_Water_Quality_merged_df[col.replace("_ugL", "_mgL")] = Hong_Kong_River_Water_Quality_merged_df[col] / 1000

In [ ]:
Hong_Kong_River_Water_Quality_merged_df = Hong_Kong_River_Water_Quality_merged_df.drop(columns=ug_cols)
Hong_Kong_River_Water_Quality_merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35196 entries, 0 to 35195
Data columns (total 18 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   River      35196 non-null  object
 1   Date       35196 non-null  object
 2   Latitude   35196 non-null  float64
 3   Longitude  35196 non-null  float64
 4   EC         35191 non-null  float64
 5   Temp_C     35187 non-null  float64
 6   SS_mgL     35185 non-null  float64
 7   pH         35184 non-null  float64
 8   TP_mgL     34692 non-null  float64
 9   NO2_N_mgL  35189 non-null  float64
 10  NO3_N_mgL  35189 non-null  float64
 11  DO_mgL     35192 non-null  float64
 12  Al_mgL     35027 non-null  float64
 13  Fe_mgL     34877 non-null  float64
 14  Mn_mgL     34995 non-null  float64
 15  Zn_mgL     35061 non-null  float64
 16  Cu_mgL     35061 non-null  float64
 17  Chl_a_mgL  18375 non-null  float64
dtypes: float64(16), object(2)
memory usage: 4.8+ MB

In [ ]:
Hong_Kong_River_Water_Quality_merged_df.head(100)

,River,Date,Latitude,Longitude,EC,Temp_C,SS_mgL,pH,TP_mgL,NO2_N_mgL,NO3_N_mgL,DO_mgL,Al_mgL,Fe_mgL,Mn_mgL,Zn_mgL,Cu_mgL,Chl_a_mgL
0,Siu Lek Yuen Nullah,29/01/1986,22.383917,114.21025,7250.0,19.9,28.0,7.4,2.80,0.004,1.800,4.9,0.10,NaN,NaN,0.050,0.0070,NaN
1,Siu Lek Yuen Nullah,25/02/1986,22.383917,114.21025,22000.0,16.9,11.0,7.4,0.86,0.064,0.200,2.6,0.02,NaN,NaN,0.010,0.0010,NaN
2,Siu Lek Yuen Nullah,25/03/1986,22.383917,114.21025,9600.0,16.6,23.0,7.3,1.50,0.150,0.880,3.0,NaN,NaN,NaN,NaN,NaN,NaN
3,Siu Lek Yuen Nullah,21/04/1986,22.383917,114.21025,2500.0,21.5,150.0,7.3,0.35,0.140,2.200,8.3,0.47,NaN,0.17,0.040,0.0050,NaN
4,Siu Lek Yuen Nullah,29/05/1986,22.383917,114.21025,22000.0,28.4,25.0,8.3,0.43,0.017,0.370,8.3,0.15,NaN,0.15,0.020,0.0020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Siu Lek Yuen Nullah,24/01/1994,22.383917,114.21025,3700.0,13.3,3.1,7.1,0.26,0.053,0.967,8.7,0.06,0.11,0.09,0.020,0.0010,NaN
96,Siu Lek Yuen Nullah,21/02/1994,22.383917,114.21025,3370.0,15.8,3.7,7.4,0.30,0.051,0.941,7.2,0.10,0.13,0.13,0.020,0.0020,NaN
97,Siu Lek Yuen Nullah,21/03/1994,22.383917,114.21025,25060.0,17.4,3.6,7.8,0.28,0.045,0.585,6.1,0.12,0.09,0.09,0.030,0.0020,NaN
98,Siu Lek Yuen Nullah,21/04/1994,22.383917,114.21025,42720.0,23.7,27.0,8.2,0.29,0.022,0.187,4.8,0.18,0.29,0.13,0.040,0.0010,NaN
99,Siu Lek Yuen Nullah,23/05/1994,22.383917,114.21025,27550.0,28.7,9.8,8.4,0.36,0.001,0.009,7.6,0.06,0.08,0.12,0.005,0.0005,NaN

In [ ]:
for col in England_River_Water_Quality_merged_df.columns:
    if England_River_Water_Quality_merged_df[col].dtype == "object" and col not in ["River", "Date"]:
        England_River_Water_Quality_merged_df[col] = England_River_Water_Quality_merged_df[col].apply(clean_numeric)

In [ ]:
England_River_Water_Quality_merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13203 entries, 0 to 13202
Data columns (total 18 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   River      13203 non-null  object
 1   Date       13203 non-null  object
 2   Latitude   13203 non-null  float64
 3   Longitude  13203 non-null  float64
 4   EC         8422 non-null   float64
 5   Temp_C     12603 non-null  float64
 6   SS_mgL     12697 non-null  float64
 7   pH         8359 non-null   float64
 8   TP_ugL     13202 non-null  float64
 9   NO2_mgL    13198 non-null  float64
 10  NO3_mgL    13202 non-null  float64
 11  DO_mgL     2534 non-null   float64
 12  Al_mgL     5312 non-null   float64
 13  Zn_ugL     6550 non-null   float64
 14  Mn_ugL     6550 non-null   float64
 15  Fe_ugL     6801 non-null   float64
 16  Cu_ugL     6550 non-null   float64
 17  Chl_a_ugL  13150 non-null  float64
dtypes: float64(16), object(2)
memory usage: 1.8+ MB

In [ ]:
# µg -> mg
England_River_Water_Quality_merged_df["TP_mgL"] = England_River_Water_Quality_merged_df["TP_ugL"] / 1000

# NO2 -> N
England_River_Water_Quality_merged_df["NO2_N_mgL"] = England_River_Water_Quality_merged_df["NO2_mgL"] * 0.304

# NO3 -> N
England_River_Water_Quality_merged_df["NO3_N_mgL"] = England_River_Water_Quality_merged_df["NO3_mgL"] * 0.226

ug_cols = ["Fe_ugL", "Mn_ugL", "Zn_ugL", "Cu_ugL", "Chl_a_ugL", "TP_ugL"]

for col in ug_cols:
    England_River_Water_Quality_merged_df[col.replace("_ugL", "_mgL")] = England_River_Water_Quality_merged_df[col] / 1000

In [ ]:
England_River_Water_Quality_merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13203 entries, 0 to 13202
Data columns (total 26 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   River      13203 non-null  object
 1   Date       13203 non-null  object
 2   Latitude   13203 non-null  float64
 3   Longitude  13203 non-null  float64
 4   EC         8422 non-null   float64
 5   Temp_C     12603 non-null  float64
 6   SS_mgL     12697 non-null  float64
 7   pH         8359 non-null   float64
 8   TP_ugL     13202 non-null  float64
 9   NO2_mgL    13198 non-null  float64
 10  NO3_mgL    13202 non-null  float64
 11  DO_mgL     2534 non-null   float64
 12  Al_mgL     5312 non-null   float64
 13  Zn_ugL     6550 non-null   float64
 14  Mn_ugL     6550 non-null   float64
 15  Fe_ugL     6801 non-null   float64
 16  Cu_ugL     6550 non-null   float64
 17  Chl_a_ugL  13150 non-null  float64
 18  TP_mgL     13202 non-null  float64
 19  NO2_N_mgL  13198 non-null  float64
 20  NO3_N_mgL  13202 non-null  float64
 21  Fe_mgL     6801 non-null   float64
 22  Mn_mgL     6550 non-null   float64
 23  Zn_mgL     6550 non-null   float64
 24  Cu_mgL     6550 non-null   float64
 25  Chl_a_mgL  13150 non-null  float64
dtypes: float64(24), object(2)
memory usage: 2.6+ MB

In [ ]:
England_River_Water_Quality_merged_df = England_River_Water_Quality_merged_df.drop(columns=ug_cols)
England_River_Water_Quality_merged_df = England_River_Water_Quality_merged_df.drop(columns=["NO2_mgL", "NO3_mgL"])
England_River_Water_Quality_merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13203 entries, 0 to 13202
Data columns (total 18 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   River      13203 non-null  object
 1   Date       13203 non-null  object
 2   Latitude   13203 non-null  float64
 3   Longitude  13203 non-null  float64
 4   EC         8422 non-null   float64
 5   Temp_C     12603 non-null  float64
 6   SS_mgL     12697 non-null  float64
 7   pH         8359 non-null   float64
 8   DO_mgL     2534 non-null   float64
 9   Al_mgL     5312 non-null   float64
 10  TP_mgL     13202 non-null  float64
 11  NO2_N_mgL  13198 non-null  float64
 12  NO3_N_mgL  13202 non-null  float64
 13  Fe_mgL     6801 non-null   float64
 14  Mn_mgL     6550 non-null   float64
 15  Zn_mgL     6550 non-null   float64
 16  Cu_mgL     6550 non-null   float64
 17  Chl_a_mgL  13150 non-null  float64
dtypes: float64(16), object(2)
memory usage: 1.8+ MB

In [ ]:
Combined_River_Water_Quality_df = pd.concat([Hong_Kong_River_Water_Quality_merged_df, England_River_Water_Quality_merged_df], ignore_index=True)

In [ ]:
Combined_River_Water_Quality_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48399 entries, 0 to 48398
Data columns (total 18 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   River      48399 non-null  object
 1   Date       48399 non-null  object
 2   Latitude   48399 non-null  float64
 3   Longitude  48399 non-null  float64
 4   EC         43613 non-null  float64
 5   Temp_C     47790 non-null  float64
 6   SS_mgL     47882 non-null  float64
 7   pH         43543 non-null  float64
 8   TP_mgL     47894 non-null  float64
 9   NO2_N_mgL  48387 non-null  float64
 10  NO3_N_mgL  48391 non-null  float64
 11  DO_mgL     37726 non-null  float64
 12  Al_mgL     40339 non-null  float64
 13  Fe_mgL     41678 non-null  float64
 14  Mn_mgL     41545 non-null  float64
 15  Zn_mgL     41611 non-null  float64
 16  Cu_mgL     41611 non-null  float64
 17  Chl_a_mgL  31525 non-null  float64
dtypes: float64(16), object(2)
memory usage: 6.6+ MB

In [ ]:
# To filter data based on 'Date' column from 2000 to 2025
Combined_River_Water_Quality_df['Date'] = pd.to_datetime(Combined_River_Water_Quality_df['Date'], dayfirst=True, errors='coerce')
Combined_River_Water_Quality_df = Combined_River_Water_Quality_df[(Combined_River_Water_Quality_df['Date'] >= '2000-01-01') & (Combined_River_Water_Quality_df['Date'] <= '2025-12-31')]
Combined_River_Water_Quality_df = Combined_River_Water_Quality_df.reset_index(drop=True)

In [ ]:
Combined_River_Water_Quality_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37098 entries, 0 to 37097
Data columns (total 18 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   River      37098 non-null  object
 1   Date       37098 non-null  datetime64[ns]
 2   Latitude   37098 non-null  float64
 3   Longitude  37098 non-null  float64
 4   EC         32317 non-null  float64
 5   Temp_C     36498 non-null  float64
 6   SS_mgL     36591 non-null  float64
 7   pH         32254 non-null  float64
 8   TP_mgL     36606 non-null  float64
 9   NO2_N_mgL  37093 non-null  float64
 10  NO3_N_mgL  37097 non-null  float64
 11  DO_mgL     26429 non-null  float64
 12  Al_mgL     29207 non-null  float64
 13  Fe_mgL     30696 non-null  float64
 14  Mn_mgL     30445 non-null  float64
 15  Zn_mgL     30445 non-null  float64
 16  Cu_mgL     30445 non-null  float64
 17  Chl_a_mgL  31525 non-null  float64
dtypes: datetime64[ns](1), float64(16), object(1)
memory usage: 5.1+ MB

In [ ]:
# Save the combined dataset to CSV
Combined_River_Water_Quality_df.to_csv(os.path.join(data_dir, "combined_river_water_quality_dataset.csv"), index=False)